### ISSUE TITLE
Insert issue

### ISSUE THREAD

**Issue by devGoresonant** [tmimori/How-to-connect-to-ERPNext-v5-API-with-PHP5#3]
When we use insert method, it throw error no json object to decode.

`case 'INSERT':
						$url = $this->_api_url.$params['doctype'];
						$ch = curl_init($url);
                                                $data_string = json_encode($params['data']);
						curl_setopt(
								$ch
								,CURLOPT_POSTFIELDS
								,$data_string
							);
                                                curl_setopt($ch, CURLOPT_HTTPHEADER, array(
                                                    'Content-Type: application/json',
                                                    'Content-Length: ' . strlen($data_string))
                                                );
                                                curl_setopt($ch,CURLOPT_POST, true);
					break;`

Please replace code with this in FrappeClient.php , Line No. 201

**Comment by tmimori** [comment]
@devGoresonant 
Could you show us the structure of your $params?
"no json object" seems that $params['data'] is invalid to be JSON. (or is not set?) .

**Comment by devGoresonant** [comment]
No, My param is correct, even i checked in FrappeClient.php, json_encode making it object successfully but the error was shown, after that i added the code from FAQ of erpnext which i shown , then code started working. You can check the code by this URL:- http://bit.ly/2tUD9NK

**Comment by tmimori** [comment]
@devGoresonant 
Is it mean that the error was a response of ERPNext?

> after that i added the code from FAQ of erpnext
Could you show us where, what or how is it? (Or could you send a Merge Request?)
And, cloud you show us the version of your ERPNext?
